name: desd
channels:
  - defaults
  - conda-forge
dependencies:
  - pyaudio
  - python
  - ca-certificates
  - certifi
  - websockets
  - streamlit
  - openssl
  - webdriver-manager
  - selenium
  - bokeh

